### ISSUE TITLE
[Tarea 2] Algún hint para la P1.2?

### ISSUE THREAD

**Issue by Okhan97** [UC-IIC3253/2021#52]
Hola,

Estoy muy atascado en esta pregunta, he investigado pero no logro llegar al 2**30 del enunciado, ¿este numero es en si un hint o no es relevante para la demostración?
Independiente de lo anterior, ¿se nos podría dar alguna pista para esta pregunta?

**Comment by mugartec** [comment]
Hola @Okhan97,

El 2<sup>30</sup> es el objetivo de la demostración, no es realmente un hint. En este sentido un (no muy útil) hint es comentarles que si puedo dividir la llave en 2 mitades que se pueden verificar independientemente, hay exactamente 2<sup>28</sup> valores posibles para cada mitad. Entonces para ambas mitades obtengo 2 * 2<sup>28</sup> = 2<sup>29</sup> que está cerca de 2<sup>30</sup> :smiley:.

Ahora un hint más profundo: De acuerdo al enunciado podemos suponer que tenemos textos planos y sus respectivas versiones cifradas. Partamos con un par (m, c:=Enc(k, m)). Obviando la permutación inicial y la permutación final de DES (que no cambian prácticamente nada), lo que conocemos es m = L<sub>0</sub> || R<sub>0</sub> y  c = L<sub>3</sub> || R<sub>3</sub>. Inspeccionando la red podemos notar que R<sub>1</sub> = L<sub>0</sub> XOR f<sub>1</sub>(R<sub>0</sub>), pero al mismo tiempo R<sub>1</sub> = R<sub>3</sub> XOR f<sub>3</sub>(L<sub>3</sub>). Teniendo esto, si me dan una llave k<sub>0</sub> yo puedo verificar si dicha llave *podría ser* la llave correcta, porque puedo calcular el lado derecho de ambas ecuaciones y ver si obtengo el mismo resultado. Ahora el hint es que, como la llave se puede dividir en dos mitades independientes que afectan exactamente los mismos bits del output de todas las f<sub>i</sub>, yo podría verificar si **la primera mitad de la llave** *podría ser* la primera mitad de la llave correcta.

Hay ciertos pasos que deben hacer con cuidado para llegar efectivamente al 2<sup>30</sup>, pero si llegan a algo cercano y el ataque está bien descrito también se va a considerar como una respuesta válida (con algún descuento de puntaje por supuesto).

Espero que sirva. Saludos!

**Comment by Okhan97** [comment]
> Inspeccionando la red podemos notar que R1 = L0 XOR f1(R0), pero al mismo tiempo R1 = R3 XOR f3(L3). 

@mugartec de donde sale esa 2da ecuación?
